title: May the thrust be with you
email: aerialroboticskgp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog"
url: "http://quadrotor-iitkgp.github.io" # the base hostname & protocol for your site
github_username:  quadrotor-iitkgp

# Build settings
markdown: kramdown
highlighter: rouge
safe: true
lsi: false
source: /blog